

'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure



Partial Public Class BDDistBHFEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=BDDistBHFEntities")

    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub


    Public Overridable Property CM001() As DbSet(Of CM001)

    Public Overridable Property CM0011() As DbSet(Of CM0011)

    Public Overridable Property TA001() As DbSet(Of TA001)

    Public Overridable Property TB001() As DbSet(Of TB001)

    Public Overridable Property TC001() As DbSet(Of TC001)

    Public Overridable Property TC002() As DbSet(Of TC002)

    Public Overridable Property TC003() As DbSet(Of TC003)

    Public Overridable Property TC004() As DbSet(Of TC004)

    Public Overridable Property TC0042() As DbSet(Of TC0042)

    Public Overridable Property TC004B() As DbSet(Of TC004B)

    Public Overridable Property TC005() As DbSet(Of TC005)

    Public Overridable Property TC0051() As DbSet(Of TC0051)

    Public Overridable Property TC006() As DbSet(Of TC006)

    Public Overridable Property TC011() As DbSet(Of TC011)

    Public Overridable Property TC0111() As DbSet(Of TC0111)

    Public Overridable Property TCA001() As DbSet(Of TCA001)

    Public Overridable Property TCA0011() As DbSet(Of TCA0011)

    Public Overridable Property TFV001() As DbSet(Of TFV001)

    Public Overridable Property TI002() As DbSet(Of TI002)

    Public Overridable Property TI0021() As DbSet(Of TI0021)

    Public Overridable Property TI004() As DbSet(Of TI004)

    Public Overridable Property TI0041() As DbSet(Of TI0041)

    Public Overridable Property TL001() As DbSet(Of TL001)

    Public Overridable Property TL002() As DbSet(Of TL002)

    Public Overridable Property TO001() As DbSet(Of TO001)

    Public Overridable Property TO001C() As DbSet(Of TO001C)

    Public Overridable Property TO004() As DbSet(Of TO004)

    Public Overridable Property TP007() As DbSet(Of TP007)

    Public Overridable Property TP008() As DbSet(Of TP008)

    Public Overridable Property TP0081() As DbSet(Of TP0081)

    Public Overridable Property TV00121() As DbSet(Of TV00121)

    Public Overridable Property TZ001() As DbSet(Of TZ001)

    Public Overridable Property ZY0021() As DbSet(Of ZY0021)

    Public Overridable Property TC0011() As DbSet(Of TC0011)

    Public Overridable Property TC0012() As DbSet(Of TC0012)

    Public Overridable Property TC0041() As DbSet(Of TC0041)

    Public Overridable Property TC004A1() As DbSet(Of TC004A1)

    Public Overridable Property TC004A2() As DbSet(Of TC004A2)

    Public Overridable Property TC0091() As DbSet(Of TC0091)

    Public Overridable Property TCA00121() As DbSet(Of TCA00121)

    Public Overridable Property TCP0011() As DbSet(Of TCP0011)

    Public Overridable Property TI003() As DbSet(Of TI003)

    Public Overridable Property TM001() As DbSet(Of TM001)

    Public Overridable Property TM0011() As DbSet(Of TM0011)

    Public Overridable Property TM0012() As DbSet(Of TM0012)

    Public Overridable Property TM0013() As DbSet(Of TM0013)

    Public Overridable Property TO0011() As DbSet(Of TO0011)

    Public Overridable Property TO0014() As DbSet(Of TO0014)

    Public Overridable Property TO001A() As DbSet(Of TO001A)

    Public Overridable Property TO002() As DbSet(Of TO002)

    Public Overridable Property TO0021() As DbSet(Of TO0021)

    Public Overridable Property TO0022() As DbSet(Of TO0022)

    Public Overridable Property TO0023() As DbSet(Of TO0023)

    Public Overridable Property TO003() As DbSet(Of TO003)

    Public Overridable Property TO0041() As DbSet(Of TO0041)

    Public Overridable Property TO0042() As DbSet(Of TO0042)

    Public Overridable Property TO0043() As DbSet(Of TO0043)

    Public Overridable Property TP001() As DbSet(Of TP001)

    Public Overridable Property TP002() As DbSet(Of TP002)

    Public Overridable Property TP003() As DbSet(Of TP003)

    Public Overridable Property TP004() As DbSet(Of TP004)

    Public Overridable Property TP006() As DbSet(Of TP006)

    Public Overridable Property TP0061() As DbSet(Of TP0061)

    Public Overridable Property TV0013() As DbSet(Of TV0013)

    Public Overridable Property vista_promconsumo() As DbSet(Of vista_promconsumo)

    Public Overridable Property vista_transacciones() As DbSet(Of vista_transacciones)

    Public Overridable Property VR_Clientes() As DbSet(Of VR_Clientes)

    Public Overridable Property VR_ClientesPendientesNota() As DbSet(Of VR_ClientesPendientesNota)

    Public Overridable Property Vr_Conciliacion() As DbSet(Of Vr_Conciliacion)

    Public Overridable Property VR_CuentasPagar_PagosRealizados() As DbSet(Of VR_CuentasPagar_PagosRealizados)

    Public Overridable Property VR_EntregaPedidos() As DbSet(Of VR_EntregaPedidos)

    Public Overridable Property VR_Facturas() As DbSet(Of VR_Facturas)

    Public Overridable Property VR_FacturasChacaltaya() As DbSet(Of VR_FacturasChacaltaya)

    Public Overridable Property vr_go_comprobanteSalidaItems() As DbSet(Of vr_go_comprobanteSalidaItems)

    Public Overridable Property vr_go_comprobanteVenta() As DbSet(Of vr_go_comprobanteVenta)

    Public Overridable Property VR_GO_DespachoXCliente() As DbSet(Of VR_GO_DespachoXCliente)

    Public Overridable Property VR_GO_DespachoXProducto() As DbSet(Of VR_GO_DespachoXProducto)

    Public Overridable Property VR_GO_DiferenciaPedidoNota() As DbSet(Of VR_GO_DiferenciaPedidoNota)

    Public Overridable Property VR_GO_EquipoPrestadoVsUltimaVenta() As DbSet(Of VR_GO_EquipoPrestadoVsUltimaVenta)

    Public Overridable Property VR_GO_EquiposPrestadoCliente() As DbSet(Of VR_GO_EquiposPrestadoCliente)

    Public Overridable Property VR_GO_FacturaVsVenta() As DbSet(Of VR_GO_FacturaVsVenta)

    Public Overridable Property VR_GO_FacturaVsVenta2() As DbSet(Of VR_GO_FacturaVsVenta2)

    Public Overridable Property VR_GO_ListarZona() As DbSet(Of VR_GO_ListarZona)

    Public Overridable Property VR_GO_PrestamoEquiposAgrupado() As DbSet(Of VR_GO_PrestamoEquiposAgrupado)

    Public Overridable Property VR_GO_PrestamoEquiposDetallado() As DbSet(Of VR_GO_PrestamoEquiposDetallado)

    Public Overridable Property vr_go_reciboCliente() As DbSet(Of vr_go_reciboCliente)

    Public Overridable Property VR_GO_SaldoPrestamoEquipo() As DbSet(Of VR_GO_SaldoPrestamoEquipo)

    Public Overridable Property VR_GO_UltimaVentaCliente() As DbSet(Of VR_GO_UltimaVentaCliente)

    Public Overridable Property vr_go_visitasDiarias() As DbSet(Of vr_go_visitasDiarias)

    Public Overridable Property VR_GraficaVentasVs() As DbSet(Of VR_GraficaVentasVs)

    Public Overridable Property VR_KadexCliente() As DbSet(Of VR_KadexCliente)

    Public Overridable Property VR_KardexInventario() As DbSet(Of VR_KardexInventario)

    Public Overridable Property VR_KardexPrestamos() As DbSet(Of VR_KardexPrestamos)

    Public Overridable Property VR_LibroVentas() As DbSet(Of VR_LibroVentas)

    Public Overridable Property VR_LibroVentasChacaltaya1() As DbSet(Of VR_LibroVentasChacaltaya1)

    Public Overridable Property VR_LibroVentasChacaltaya2() As DbSet(Of VR_LibroVentasChacaltaya2)

    Public Overridable Property Vr_Mam_Clientes() As DbSet(Of Vr_Mam_Clientes)

    Public Overridable Property VR_Mam_Conciliacion() As DbSet(Of VR_Mam_Conciliacion)

    Public Overridable Property Vr_Mam_Credito_Cliente() As DbSet(Of Vr_Mam_Credito_Cliente)

    Public Overridable Property Vr_Mam_ProductoVenta() As DbSet(Of Vr_Mam_ProductoVenta)

    Public Overridable Property VR_MO_GetPedidos() As DbSet(Of VR_MO_GetPedidos)

    Public Overridable Property VR_Nota_de_Venta() As DbSet(Of VR_Nota_de_Venta)

    Public Overridable Property VR_Pagos() As DbSet(Of VR_Pagos)

    Public Overridable Property VR_ProductosMesas() As DbSet(Of VR_ProductosMesas)

    Public Overridable Property VR_ResumenNotas() As DbSet(Of VR_ResumenNotas)

    Public Overridable Property VR_SaldoCliente() As DbSet(Of VR_SaldoCliente)

    Public Overridable Property VR_stockActual() As DbSet(Of VR_stockActual)

    Public Overridable Property VR_StockDisponible() As DbSet(Of VR_StockDisponible)

    Public Overridable Property VR_UtilidadPorProducto() As DbSet(Of VR_UtilidadPorProducto)

    Public Overridable Property Vr_VentasVendedor12Meses() As DbSet(Of Vr_VentasVendedor12Meses)

    Public Overridable Property Vr_VentasVendidas() As DbSet(Of Vr_VentasVendidas)

    Public Overridable Property VR_VistaPedido_PrecioCosto() As DbSet(Of VR_VistaPedido_PrecioCosto)


End Class

