
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class CM0011

    Public Property mbnumi As Integer

    Public Property mb_manumi As Nullable(Of Integer)

    Public Property mbcodvendedor As Nullable(Of Integer)

    Public Property mbest As Nullable(Of Integer)

    Public Property mbfact As Nullable(Of Date)

    Public Property mbhact As String

    Public Property mbuact As String


End Class
