
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class CM001

    Public Property manumi As Integer

    Public Property mamesa As Nullable(Of Integer)

    Public Property macodrepart As Nullable(Of Integer)

    Public Property maest As Nullable(Of Integer)

    Public Property mafact As Nullable(Of Date)

    Public Property mahact As String

    Public Property mauact As String


End Class
