
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TA001

    Public Property aaId As Integer

    Public Property aaalias As String

    Public Property aadesc As String

    Public Property aatipo As Nullable(Of Integer)

    Public Property aasize As Nullable(Of Integer)

    Public Property aadec As Nullable(Of Integer)


End Class
