
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TB001

    Public Property banumi As Integer

    Public Property banum As Nullable(Of Integer)

    Public Property baproc As String

    Public Property balinea As Nullable(Of Integer)

    Public Property bamensaje As String

    Public Property batipo As Nullable(Of Integer)

    Public Property bafact As Nullable(Of Date)

    Public Property bahact As String

    Public Property bauact As String


End Class
