
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TC0091

    Public Property clnumi As Nullable(Of Integer)

    Public Property clcodu As Nullable(Of Integer)

    Public Property clshow As Nullable(Of Boolean)

    Public Property cllin As Integer

    Public Property clcopy As Nullable(Of Boolean)


End Class
