
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TC006

    Public Property cfid As Integer

    Public Property cfdesc As String

    Public Property cffact As Nullable(Of Date)

    Public Property cfhact As String

    Public Property cfuact As String


End Class
