
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TC0051

    Public Property ceId As Integer

    Public Property cecon As Nullable(Of Integer)

    Public Property cenum As Nullable(Of Integer)

    Public Property cedesc As String

    Public Property cefact As Nullable(Of Date)

    Public Property cehact As String

    Public Property ceuact As String


End Class
