
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TC002

    Public Property cbnumi As Integer

    Public Property cbdesc As String

    Public Property cbdirec As String

    Public Property cbtelef As String

    Public Property cbcat As Nullable(Of Integer)

    Public Property cbsal As Nullable(Of Decimal)

    Public Property cbci As String

    Public Property cbobs As String

    Public Property cbfnac As Nullable(Of Date)

    Public Property cbfing As Nullable(Of Date)

    Public Property cbfret As Nullable(Of Date)

    Public Property cbfot As String

    Public Property cbest As Nullable(Of Boolean)

    Public Property cbeciv As String

    Public Property cbplan As Nullable(Of Integer)

    Public Property cbreloj As Nullable(Of Integer)

    Public Property cbfact As Nullable(Of Date)

    Public Property cbhact As String

    Public Property cbuact As String


End Class
