
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TC004

    Public Property ccnumi As Integer

    Public Property cccod As String

    Public Property ccdesc As String

    Public Property cczona As Nullable(Of Integer)

    Public Property ccdct As Integer

    Public Property ccdctnum As String

    Public Property ccdirec As String

    Public Property cctelf1 As String

    Public Property cctelf2 As String

    Public Property cccat As Nullable(Of Integer)

    Public Property ccest As Nullable(Of Integer)

    Public Property cclat As Nullable(Of Decimal)

    Public Property cclongi As Nullable(Of Decimal)

    Public Property ccprconsu As Nullable(Of Integer)

    Public Property cceven As Nullable(Of Boolean)

    Public Property ccobs As String

    Public Property ccfnac As Nullable(Of Date)

    Public Property ccnomfac As String

    Public Property ccnit As String

    Public Property ccultped As Nullable(Of Date)

    Public Property ccfecing As Nullable(Of Date)

    Public Property ccultvent As Nullable(Of Date)

    Public Property ccrecven As Nullable(Of Integer)

    Public Property ccsupven As Nullable(Of Integer)

    Public Property ccpreven As Nullable(Of Integer)

    Public Property ccemail As String

    Public Property ccref As String

    Public Property ccpass As String

    Public Property ccfact As Nullable(Of Date)

    Public Property cchact As String

    Public Property ccuact As String


End Class
