
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TC004A2

    Public Property ccabnumi As Integer

    Public Property ccabtc4anumi As Nullable(Of Integer)

    Public Property ccabprod As Nullable(Of Integer)

    Public Property ccabcant As Nullable(Of Decimal)


End Class
