
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TC001

    Public Property canumi As Integer

    Public Property cacod As String

    Public Property cadesc As String

    Public Property cadesc2 As String

    Public Property cacat As Nullable(Of Integer)

    Public Property caimg As String

    Public Property castc As Nullable(Of Boolean)

    Public Property caest As Nullable(Of Boolean)

    Public Property caserie As Nullable(Of Boolean)

    Public Property capcom As Nullable(Of Integer)

    Public Property cafing As Nullable(Of Date)

    Public Property cacemp As Nullable(Of Integer)

    Public Property cafact As Nullable(Of Date)

    Public Property cahact As String

    Public Property cauact As String

    Public Property cacbarra As String

    Public Property casmin As Nullable(Of Integer)

    Public Property cagr1 As Nullable(Of Integer)

    Public Property cagr2 As Nullable(Of Integer)

    Public Property cagr3 As Nullable(Of Integer)

    Public Property cagr4 As Nullable(Of Integer)

    Public Property caumed As Nullable(Of Integer)

    Public Property cauventa As Nullable(Of Integer)

    Public Property caumax As Nullable(Of Integer)

    Public Property caconv As Nullable(Of Decimal)


End Class
