
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TC005

    Public Property cdId As Integer

    Public Property cdcon As Nullable(Of Integer)

    Public Property cddesc As String

    Public Property cdver As Nullable(Of Boolean)

    Public Property cdfact As Nullable(Of Date)

    Public Property cdhact As String

    Public Property cduact As String


End Class
