
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TC003

    Public Property chnumi As Integer

    Public Property chcprod As String

    Public Property chcatcl As Nullable(Of Integer)

    Public Property chprecio As Nullable(Of Decimal)

    Public Property chfact As Nullable(Of Date)

    Public Property chhact As String

    Public Property chuact As String


End Class
