
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TC004A1

    Public Property ccaanumi As Integer

    Public Property ccatc4anumi As Nullable(Of Integer)

    Public Property ccaandia As Nullable(Of Integer)


End Class
