
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TC0011

    Public Property cicod As String

    Public Property cilin As Nullable(Of Integer)

    Public Property cinserie As String

    Public Property cieserie As Nullable(Of Boolean)

    Public Property ciest As Nullable(Of Boolean)


End Class
