
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TC0111

    Public Property coline As Integer

    Public Property conumi As Nullable(Of Integer)

    Public Property coing1 As String

    Public Property cosal1 As String

    Public Property coing2 As String

    Public Property cosal2 As String


End Class
