
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TC011

    Public Property cnnumi As Integer

    Public Property cnfdoc As Nullable(Of Date)

    Public Property cnobs As String

    Public Property cnest As Nullable(Of Integer)

    Public Property cnfact As Nullable(Of Date)

    Public Property cnhact As String

    Public Property cnuact As String


End Class
