
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TCA001

    Public Property caanumi As Integer

    Public Property caafdoc As Nullable(Of Date)

    Public Property caaprov As Nullable(Of Integer)

    Public Property caanfac As String

    Public Property caaobs As String

    Public Property caafact As Nullable(Of Date)

    Public Property caahact As String

    Public Property caauact As String

    Public Property caatven As Nullable(Of Integer)

    Public Property caafvcred As Nullable(Of Date)

    Public Property caamon As Nullable(Of Integer)

    Public Property caaest As Nullable(Of Integer)

    Public Property caadesc As Nullable(Of Decimal)

    Public Property caatotal As Nullable(Of Decimal)

    Public Property caaemision As Nullable(Of Integer)

    Public Property caaconsigna As Nullable(Of Integer)


End Class
