
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TCA0011

    Public Property cabnumi As Integer

    Public Property cabtc1numi As Nullable(Of Integer)

    Public Property cabcant As Nullable(Of Decimal)

    Public Property cabpcom As Nullable(Of Decimal)

    Public Property cabputi As Nullable(Of Decimal)

    Public Property cabpven As Nullable(Of Decimal)

    Public Property cabnfr As String

    Public Property cabstocka As Nullable(Of Decimal)

    Public Property cabstockf As Nullable(Of Decimal)

    Public Property cabtca1numi As Nullable(Of Integer)


End Class
