
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TCP0011

    Public Property cpbnumi As Nullable(Of Integer)

    Public Property cpbfdoc As Nullable(Of Date)

    Public Property cpbmonto As Nullable(Of Decimal)

    Public Property cpblin As Integer

    Public Property cpbfact As Nullable(Of Date)

    Public Property cpbhact As String

    Public Property cpbuact As String


End Class
