
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TI004

    Public Property ieid As Integer

    Public Property iefdoc As Nullable(Of Date)

    Public Property ieconcep As Nullable(Of Integer)

    Public Property ieobs As String

    Public Property ietip As Nullable(Of Integer)

    Public Property ieidcab As Nullable(Of Integer)

    Public Property ieiddet As Nullable(Of Integer)

    Public Property iefact As Nullable(Of Date)

    Public Property iehact As String

    Public Property ieuact As String


End Class
