
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TI0041

    Public Property ifid As Integer

    Public Property ifieid As Nullable(Of Integer)

    Public Property ifcli As Nullable(Of Integer)

    Public Property ifmon As Nullable(Of Decimal)


End Class
