
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TL002

    Public Property ldnumi As Integer

    Public Property ldchof As Nullable(Of Integer)

    Public Property ldfec As Nullable(Of Date)

    Public Property ldhora As String

    Public Property lblat As Nullable(Of Decimal)

    Public Property lblongi As Nullable(Of Decimal)


End Class
