
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TL001

    Public Property lanumi As Integer

    Public Property lacity As Nullable(Of Integer)

    Public Property laprovi As Nullable(Of Integer)

    Public Property lazona As Nullable(Of Integer)

    Public Property lacolor As String

    Public Property lafact As Nullable(Of Date)

    Public Property lahact As String

    Public Property lauact As String


End Class
