
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TM001

    Public Property ibid As Integer

    Public Property ibfdoc As Nullable(Of Date)

    Public Property ibconcep As Nullable(Of Integer)

    Public Property ibobs As String

    Public Property ibest As Nullable(Of Integer)

    Public Property ibalm As Nullable(Of Integer)

    Public Property ibiddc As Nullable(Of Integer)

    Public Property ibidchof As Nullable(Of Integer)

    Public Property ibidvent As Nullable(Of Integer)

    Public Property ibidconcil As Nullable(Of Integer)

    Public Property ibfact As Nullable(Of Date)

    Public Property ibhact As String

    Public Property ibuact As String


End Class
