
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TM0013

    Public Property idnumi As Integer

    Public Property idtm1id As Nullable(Of Integer)

    Public Property idto1numi As Nullable(Of Integer)

    Public Property idtipo As Nullable(Of Integer)


End Class
