
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TO0022

    Public Property ofnumi As Nullable(Of Integer)

    Public Property oflin As Nullable(Of Integer)

    Public Property ofccli As Nullable(Of Integer)

    Public Property ofcprod As String

    Public Property ofcant As Nullable(Of Integer)

    Public Property ofcant2 As Nullable(Of Integer)

    Public Property ofest As Nullable(Of Integer)

    Public Property ofest2 As Nullable(Of Integer)

    Public Property ofid As Integer


End Class
