
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TO004

    Public Property ohnumi As Integer

    Public Property ohfec As Nullable(Of Date)

    Public Property ohcon As Nullable(Of Integer)

    Public Property ohest As Nullable(Of Integer)

    Public Property ohfact As Nullable(Of Date)

    Public Property ohhact As String

    Public Property ohuact As String


End Class
