
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TO0014

    Public Property ofnumi As Integer

    Public Property ofnumiped As Integer

    Public Property ofest As Nullable(Of Integer)

    Public Property ofobs As String

    Public Property oftip As Nullable(Of Integer)

    Public Property ofconcep As Nullable(Of Integer)

    Public Property offact As Nullable(Of Date)

    Public Property ofhact As String

    Public Property ofuact As String


End Class
