
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TO0043

    Public Property oknumi As Integer

    Public Property oknumi2 As Nullable(Of Integer)

    Public Property okcprod As Nullable(Of Integer)

    Public Property okccant As Nullable(Of Decimal)

    Public Property okprecio As Nullable(Of Decimal)


End Class
