
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TO0011

    Public Property obnumi As Integer

    Public Property obcprod As String

    Public Property obpcant As Nullable(Of Decimal)

    Public Property obpbase As Nullable(Of Decimal)

    Public Property obptot As Nullable(Of Decimal)


End Class
