
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TO001A

    Public Property oaanumi As Integer

    Public Property oaato1numi As Nullable(Of Integer)

    Public Property oaanumiprev As Nullable(Of Integer)

    Public Property oaaentrega As Nullable(Of Integer)

    Public Property oaacaja As Nullable(Of Integer)


End Class
