
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TO0023

    Public Property ojnumi As Integer

    Public Property ojtc1 As Nullable(Of Integer)

    Public Property ojtc4 As Nullable(Of Integer)

    Public Property ojcant As Nullable(Of Integer)

    Public Property ojest As Nullable(Of Integer)

    Public Property ojdif As Nullable(Of Boolean)

    Public Property ojto1 As Nullable(Of Integer)

    Public Property ojto2 As Nullable(Of Integer)

    Public Property ojfact As Nullable(Of Date)

    Public Property ojhact As String

    Public Property ojuact As String


End Class
