
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TO0021

    Public Property oenumi As Integer

    Public Property oelin As Nullable(Of Integer)

    Public Property oencli As Nullable(Of Integer)

    Public Property oeefec As Nullable(Of Decimal)

    Public Property oecred As Nullable(Of Decimal)

    Public Property oenrec As String

    Public Property oenfac As String

    Public Property oenped As Nullable(Of Integer)

    Public Property oetipo As String


End Class
