
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TO0042

    Public Property ojnumi As Integer

    Public Property ojnumi2 As Nullable(Of Integer)

    Public Property ojccli As Nullable(Of Integer)

    Public Property ojnota As String

    Public Property ojobs As String

    Public Property ojprecon As Nullable(Of Decimal)

    Public Property ojprecre As Nullable(Of Decimal)

    Public Property ojdesc As Nullable(Of Decimal)


End Class
