
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TO002

    Public Property odnumi As Integer

    Public Property odnota As Nullable(Of Integer)

    Public Property odfdoc As Nullable(Of Date)

    Public Property odtprod As Nullable(Of Integer)

    Public Property odrepa As Nullable(Of Integer)

    Public Property odtap As Nullable(Of Integer)

    Public Property oddes As Nullable(Of Double)

    Public Property odfact As Nullable(Of Date)

    Public Property odhact As String

    Public Property oduact As String


End Class
