
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TO0041

    Public Property oinumi As Integer

    Public Property oinumi2 As Nullable(Of Integer)

    Public Property oicprod As Nullable(Of Integer)

    Public Property oivmovil As Nullable(Of Decimal)

    Public Property oisubtotal As Nullable(Of Decimal)

    Public Property oicant As Nullable(Of Decimal)


End Class
