
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TO003

    Public Property ognumi As Integer

    Public Property ogrec As Nullable(Of Integer)

    Public Property ogfdoc As Nullable(Of Date)

    Public Property ogcli As Nullable(Of Integer)

    Public Property ogmon As Nullable(Of Decimal)

    Public Property ognota As Nullable(Of Integer)

    Public Property ogtprod As Nullable(Of Integer)

    Public Property ogfact As Nullable(Of Date)

    Public Property oghact As String

    Public Property oguact As String


End Class
