
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TP0061

    Public Property phnumi As Integer

    Public Property phfsal As Nullable(Of Date)

    Public Property phfing As Nullable(Of Date)

    Public Property phdias As Nullable(Of Integer)


End Class
