
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TP004

    Public Property penumi As Integer

    Public Property pemeses As Nullable(Of Integer)

    Public Property pedias As Nullable(Of Integer)

    Public Property pefvig As Nullable(Of Date)

    Public Property petipo As Nullable(Of Boolean)

    Public Property pefact As Nullable(Of Date)

    Public Property pehact As String

    Public Property peuact As String


End Class
