
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TP008

    Public Property pknumi As Integer

    Public Property pkper As Nullable(Of Integer)

    Public Property pkmes As Nullable(Of Integer)

    Public Property pkanio As Nullable(Of Integer)

    Public Property pkfact As Nullable(Of Date)

    Public Property pkhact As String

    Public Property pkuact As String


End Class
