
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TP006

    Public Property pgnumi As Integer

    Public Property pgcper As Nullable(Of Integer)

    Public Property pgfdoc As Nullable(Of Date)

    Public Property pgest As Nullable(Of Integer)

    Public Property pgobs As String

    Public Property pgfsal As Nullable(Of Date)

    Public Property pgfing As Nullable(Of Date)

    Public Property pgdias As Nullable(Of Integer)

    Public Property pgfact As Nullable(Of Date)

    Public Property pghact As String

    Public Property pguact As String


End Class
