
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TP001

    Public Property panumi As Integer

    Public Property patipo As Nullable(Of Boolean)

    Public Property pavalor As Nullable(Of Decimal)

    Public Property pacper As Nullable(Of Integer)

    Public Property paobs As String

    Public Property pavenc As Nullable(Of Integer)

    Public Property pafvenc As Nullable(Of Date)

    Public Property pafact As Nullable(Of Date)

    Public Property pahact As String

    Public Property pauact As String


End Class
