
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TP002

    Public Property pbnumi As Integer

    Public Property pbcper As Nullable(Of Integer)

    Public Property pbano As Nullable(Of Integer)

    Public Property pbmes As Nullable(Of Integer)

    Public Property pbfact As Nullable(Of Date)

    Public Property pbhact As String

    Public Property pbuact As String


End Class
