
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TP007

    Public Property pinumi As Integer

    Public Property picper As Nullable(Of Integer)

    Public Property pifdoc As Nullable(Of Date)

    Public Property piturno As Nullable(Of Integer)

    Public Property pifact As Nullable(Of Date)

    Public Property pihact As String

    Public Property piuact As String


End Class
