
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TP0081

    Public Property plline As Integer

    Public Property plnumi As Nullable(Of Integer)

    Public Property plcon As Nullable(Of Integer)

    Public Property pldesc As String

    Public Property plmonto As Nullable(Of Decimal)

    Public Property plnumibd As Nullable(Of Integer)


End Class
