
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TP003

    Public Property pdnumi As Integer

    Public Property pdmeses As Nullable(Of Integer)

    Public Property pdmonto As Nullable(Of Decimal)

    Public Property pdfact As Nullable(Of Date)

    Public Property pdhact As String

    Public Property pduact As String


End Class
