
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TV0013

    Public Property tenumi As Integer

    Public Property tefdoc As Nullable(Of Date)

    Public Property tety4vend As Nullable(Of Integer)

    Public Property teobs As String

    Public Property tefact As Nullable(Of Date)

    Public Property tehact As String

    Public Property teuact As String


End Class
