
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TV001

    Public Property tanumi As Integer

    Public Property taalm As Nullable(Of Integer)

    Public Property tafdoc As Nullable(Of Date)

    Public Property taven As Nullable(Of Integer)

    Public Property tatven As Nullable(Of Integer)

    Public Property tafvcr As Nullable(Of Date)

    Public Property taclpr As Integer

    Public Property tamon As Nullable(Of Integer)

    Public Property taest As Nullable(Of Integer)

    Public Property tatotal As Nullable(Of Decimal)

    Public Property tafact As Nullable(Of Date)

    Public Property tahact As String

    Public Property tauact As String


End Class
