
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TV0011

    Public Property tbnumi As Integer

    Public Property tbtv1numi As Nullable(Of Integer)

    Public Property tbty5prod As Nullable(Of Integer)

    Public Property tbest As Nullable(Of Integer)

    Public Property tbcmin As Nullable(Of Decimal)

    Public Property tbumin As Nullable(Of Integer)

    Public Property tbpbas As Nullable(Of Decimal)

    Public Property tbptot As Nullable(Of Decimal)

    Public Property tbporc As Nullable(Of Decimal)

    Public Property tbdesc As Nullable(Of Decimal)

    Public Property tbtotdesc As Nullable(Of Decimal)

    Public Property tbobs As String

    Public Property tbpcos As Nullable(Of Decimal)

    Public Property tbptot2 As Nullable(Of Decimal)

    Public Property tbfact As Nullable(Of Date)

    Public Property tbhact As String

    Public Property tbuact As String


End Class
