
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TZ001

    Public Property zaline As Integer

    Public Property zacper As Nullable(Of Integer)

    Public Property zafecha As Nullable(Of Date)

    Public Property zahora As String

    Public Property zaest As Nullable(Of Integer)


End Class
