
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class vista_promconsumo

    Public Property ccnumi As Integer

    Public Property ccdesc As String

    Public Property cczona As Nullable(Of Integer)

    Public Property cctelf1 As String

    Public Property ccdirec As String

    Public Property ccest As Nullable(Of Integer)

    Public Property ccprconsu As Nullable(Of Integer)

    Public Property fTentativa As Nullable(Of Date)


End Class
