
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class Vr_Conciliacion

    Public Property Fecha As Date

    Public Property Chofer As Nullable(Of Integer)

    Public Property Prod As Nullable(Of Integer)

    Public Property Cant As Nullable(Of Decimal)


End Class
