
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class VR_CuentasPagar_PagosRealizados

    Public Property cpaprov As Nullable(Of Integer)

    Public Property cmdesc As String

    Public Property cpanumi As Nullable(Of Integer)

    Public Property cpaobs As String

    Public Property cpafven As Nullable(Of Date)

    Public Property cpamonto As Nullable(Of Decimal)

    Public Property saldo As Nullable(Of Decimal)

    Public Property pagado As Nullable(Of Decimal)

    Public Property cpblin As Integer

    Public Property cpbmonto As Nullable(Of Decimal)

    Public Property cpbfdoc As Nullable(Of Date)

    Public Property mora As Nullable(Of Integer)


End Class
