
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class VR_ClientesPendientesNota

    Public Property ccnumi As Nullable(Of Integer)

    Public Property ccdctnum As String

    Public Property ccdesc As String

    Public Property ccdirec As String

    Public Property zon As Nullable(Of Integer)

    Public Property nzon As String

    Public Property codP As String

    Public Property can As Nullable(Of Integer)

    Public Property tot As Nullable(Of Decimal)

    Public Property ped As Integer

    Public Property cacat As Nullable(Of Integer)


End Class
