
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class VR_FacturasChacaltaya

    Public Property odfdoc As Nullable(Of Date)

    Public Property ccnumi As Integer

    Public Property ccdesc As String

    Public Property ccdctnum As String

    Public Property odnota As Nullable(Of Integer)

    Public Property oenfac As String

    Public Property oeefec As Nullable(Of Decimal)


End Class
