
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class VR_Facturas

    Public Property fvanumi As Integer

    Public Property fvafec As Nullable(Of Date)

    Public Property fvanfac As Nullable(Of Integer)

    Public Property fvaautoriz As Nullable(Of Double)

    Public Property fvaest As Nullable(Of Integer)

    Public Property fvanitcli As String

    Public Property fvacodcli As Nullable(Of Integer)

    Public Property fvadescli1 As String

    Public Property fvadescli2 As String

    Public Property fvastot As Nullable(Of Double)

    Public Property fvaimpsi As Nullable(Of Double)

    Public Property fvaimpeo As Nullable(Of Double)

    Public Property fvaimptc As Nullable(Of Double)

    Public Property fvasubtotal As Nullable(Of Double)

    Public Property fvadesc As Nullable(Of Double)

    Public Property fvatotal As Nullable(Of Double)

    Public Property fvadebfis As Nullable(Of Double)

    Public Property fvaccont As String

    Public Property fvaflim As Nullable(Of Date)

    Public Property fvaimgqr As Byte()

    Public Property fvaalm As Nullable(Of Integer)

    Public Property fvanumi2 As Integer

    Public Property fvbnumi As Nullable(Of Integer)

    Public Property fvbcprod As String

    Public Property fvbdesprod As String

    Public Property fvbcant As Nullable(Of Integer)

    Public Property fvbprecio As Nullable(Of Double)

    Public Property fvbnumi2 As Nullable(Of Integer)


End Class
