
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class VR_GO_DiferenciaPedidoNota

    Public Property numi As Integer

    Public Property fecha As Nullable(Of Date)

    Public Property ccli As Nullable(Of Integer)

    Public Property cpro As Nullable(Of Integer)

    Public Property npro As String

    Public Property pedido As Nullable(Of Integer)

    Public Property nota As Nullable(Of Integer)

    Public Property cped As Integer

    Public Property cnot As Nullable(Of Integer)

    Public Property dif As Nullable(Of Integer)

    Public Property hora As String

    Public Property usuario As String


End Class
