
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class VR_GO_EquiposPrestadoCliente

    Public Property codbd As Integer

    Public Property codigo As String

    Public Property contacto As String

    Public Property carrito As Nullable(Of Integer)

    Public Property botellone As Nullable(Of Integer)

    Public Property nombre As String

    Public Property direccion As String


End Class
