
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class vr_go_visitasDiarias

    Public Property ccnumi As Integer

    Public Property cccod As String

    Public Property ccdesc As String

    Public Property cctelf1 As String

    Public Property ccdirec As String

    Public Property cczona As Nullable(Of Integer)

    Public Property ccatacu As Nullable(Of Integer)

    Public Property ntacu As String

    Public Property ccafini As Nullable(Of Date)

    Public Property ccaffin As Nullable(Of Date)

    Public Property ccafre As Nullable(Of Integer)

    Public Property nfre As String

    Public Property ccaest As Nullable(Of Integer)

    Public Property ccaobs As String

    Public Property ccaandia As Nullable(Of Integer)

    Public Property ccabprod As Nullable(Of Integer)

    Public Property nprod As String

    Public Property ccabcant As Nullable(Of Decimal)


End Class
