
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class vr_go_comprobanteVenta

    Public Property codigo As Integer

    Public Property fecha As Nullable(Of Date)

    Public Property conciliacion As Nullable(Of Integer)

    Public Property distribuidor As Nullable(Of Integer)

    Public Property ndistribuidor As String

    Public Property est As Nullable(Of Integer)

    Public Property nest As String

    Public Property cliente As Nullable(Of Integer)

    Public Property ncliente As String

    Public Property contado As Nullable(Of Decimal)

    Public Property credito As Nullable(Of Decimal)

    Public Property descuento As Nullable(Of Decimal)

    Public Property totalContado As Nullable(Of Decimal)

    Public Property factura As String

    Public Property ojobs As String


End Class
