
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class VR_GO_FacturaVsVenta2

    Public Property lin As Nullable(Of Integer)

    Public Property nota As Nullable(Of Integer)

    Public Property fecha As Nullable(Of Date)

    Public Property ccli As Nullable(Of Integer)

    Public Property ncli As String

    Public Property mefec As Nullable(Of Decimal)

    Public Property mcred As Nullable(Of Decimal)

    Public Property mfact As Nullable(Of Decimal)

    Public Property recibo As String

    Public Property factura As String

    Public Property tipo As String


End Class
