
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class VR_GO_PrestamoEquiposAgrupado

    Public Property chnumi As Integer

    Public Property ccdesc As String

    Public Property chcod As String

    Public Property chdesc As String

    Public Property chtmov As Nullable(Of Integer)

    Public Property cpdesc As String

    Public Property cant As Nullable(Of Double)

    Public Property cpmov As Nullable(Of Integer)


End Class
