
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class VR_GraficaVentasVs

    Public Property oanumi As Integer

    Public Property oafdoc As Nullable(Of Date)

    Public Property total As Nullable(Of Decimal)

    Public Property anio As Nullable(Of Integer)

    Public Property mes1 As Nullable(Of Integer)

    Public Property mes2 As String


End Class
