
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class VR_GO_UltimaVentaCliente

    Public Property numi As Integer

    Public Property rsoc As String

    Public Property fultven As Nullable(Of Date)

    Public Property telf As String

    Public Property direc As String

    Public Property czona As Nullable(Of Integer)

    Public Property dpto As String

    Public Property prov As String

    Public Property zona As String

    Public Property est As Nullable(Of Integer)


End Class
