
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class VR_GO_ListarZona

    Public Property numi As Integer

    Public Property ccity As Nullable(Of Integer)

    Public Property ncity As String

    Public Property cprov As Nullable(Of Integer)

    Public Property nprov As String

    Public Property czona As Nullable(Of Integer)

    Public Property nzona As String

    Public Property color As String

    Public Property fact As Nullable(Of Date)

    Public Property hact As String

    Public Property uact As String


End Class
