
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class vr_go_comprobanteSalidaItems

    Public Property id As Integer

    Public Property fecha As Nullable(Of Date)

    Public Property concepto As Nullable(Of Integer)

    Public Property nconcepto As String

    Public Property obs As String

    Public Property repatidor As Nullable(Of Integer)

    Public Property nrepatidor As String

    Public Property conciliacion As Nullable(Of Integer)

    Public Property producto As Integer

    Public Property nproducto As String

    Public Property cantidad As Nullable(Of Decimal)


End Class
