
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class vr_go_reciboCliente

    Public Property oanumi As Integer

    Public Property oafdoc As Nullable(Of Date)

    Public Property cedesc As String

    Public Property oarepa As Nullable(Of Integer)

    Public Property cbdesc As String

    Public Property ccnumi As Integer

    Public Property cccod As String

    Public Property ccdesc As String

    Public Property obpcant As Nullable(Of Decimal)

    Public Property cadesc2 As String

    Public Property obpbase As Nullable(Of Decimal)

    Public Property obptot As Nullable(Of Decimal)

    Public Property cctelf1 As String

    Public Property ccdirec As String

    Public Property oaobs As String

    Public Property oaanumiprev As Nullable(Of Integer)

    Public Property cbdesc2 As String


End Class
