
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class VR_KadexCliente

    Public Property tprod As Nullable(Of Integer)

    Public Property grupo As String

    Public Property nnota As Nullable(Of Integer)

    Public Property ccli As Nullable(Of Integer)

    Public Property nombre As String

    Public Property fecha As Nullable(Of Date)

    Public Property concepto As String

    Public Property con As Nullable(Of Decimal)

    Public Property cre As Nullable(Of Decimal)

    Public Property pago As Nullable(Of Decimal)

    Public Property saldo As Nullable(Of Decimal)

    Public Property nota As Nullable(Of Integer)

    Public Property tipo As String

    Public Property factura As Nullable(Of Integer)


End Class
