
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class VR_KardexInventario

    Public Property id As Integer

    Public Property fdoc As Nullable(Of Date)

    Public Property concep As Integer

    Public Property descConcep As String

    Public Property obs As String

    Public Property est As Nullable(Of Integer)

    Public Property alm As Nullable(Of Integer)

    Public Property id2 As Integer

    Public Property cprod As Nullable(Of Integer)

    Public Property descProd As String

    Public Property desc2Prod As String

    Public Property cant As Nullable(Of Decimal)

    Public Property saldo As Decimal

    Public Property nombreCliente As String


End Class
