
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class VR_KardexPrestamos

    Public Property chnumi As Integer

    Public Property ccdesc As String

    Public Property cczona As Nullable(Of Integer)

    Public Property cedesc As String

    Public Property chfec As Nullable(Of Date)

    Public Property chdesc As String

    Public Property tipo As String

    Public Property chnota As Nullable(Of Integer)

    Public Property chcan As Nullable(Of Double)

    Public Property chmonbs As Nullable(Of Double)

    Public Property chmonsus As Nullable(Of Double)

    Public Property chtmov As Nullable(Of Integer)


End Class
