
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class VR_LibroVentasChacaltaya2

    Public Property esp As Integer

    Public Property nro As Nullable(Of Long)

    Public Property fec As Nullable(Of Date)

    Public Property fac As String

    Public Property aut As Integer

    Public Property est As String

    Public Property nit As String

    Public Property nom As String

    Public Property nfac As String

    Public Property a As Nullable(Of Decimal)

    Public Property b As Nullable(Of Decimal)

    Public Property c As Nullable(Of Decimal)

    Public Property d As Nullable(Of Decimal)

    Public Property e As Nullable(Of Decimal)

    Public Property f As Nullable(Of Decimal)

    Public Property g As Nullable(Of Decimal)

    Public Property h As Nullable(Of Decimal)

    Public Property ccon As String


End Class
