
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class VR_LibroVentas

    Public Property fvanumi As Integer

    Public Property fvafec As Nullable(Of Date)

    Public Property fvanfac As Nullable(Of Integer)

    Public Property fvaautoriz As Nullable(Of Double)

    Public Property fvaest As String

    Public Property fvanitcli As String

    Public Property fvadescli As String

    Public Property fvastot As Nullable(Of Double)

    Public Property fvaimpsi As Nullable(Of Double)

    Public Property fvaimpeo As Nullable(Of Double)

    Public Property fvaimptc As Nullable(Of Double)

    Public Property fvasubtotal As Nullable(Of Double)

    Public Property fvadesc As Nullable(Of Double)

    Public Property fvatotal As Nullable(Of Double)

    Public Property fvadebfis As Nullable(Of Double)

    Public Property fvaccont As String

    Public Property fvaflim As Nullable(Of Date)

    Public Property fvaalm As Nullable(Of Integer)

    Public Property scnom As String


End Class
