
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class Vr_Mam_Credito_Cliente

    Public Property pago As Decimal

    Public Property numicliente As Integer

    Public Property cliente As String

    Public Property direc As String

    Public Property telf1 As String

    Public Property contacto As String

    Public Property codven As Nullable(Of Integer)

    Public Property ydlcred As Integer

    Public Property tanumi As Integer

    Public Property tafdoc As Nullable(Of Date)

    Public Property tafvcr As Nullable(Of Date)

    Public Property yddias As Integer

    Public Property tatotal As Nullable(Of Decimal)

    Public Property desven As String

    Public Property TotCredit As Nullable(Of Decimal)

    Public Property pendiente As Nullable(Of Decimal)


End Class
