
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class Vr_Mam_ProductoVenta

    Public Property categoria As String

    Public Property numiProducto As Integer

    Public Property producto As String

    Public Property NombreCorto As String

    Public Property empresa As String

    Public Property cantidad As Nullable(Of Decimal)

    Public Property obpbase As Nullable(Of Decimal)

    Public Property TotalVenta As Nullable(Of Decimal)


End Class
