
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class VR_Mam_Conciliacion

    Public Property canumi As Integer

    Public Property cadesc As String

    Public Property columna1 As Nullable(Of Integer)

    Public Property columna2 As Nullable(Of Integer)

    Public Property columna3 As Nullable(Of Integer)

    Public Property columna4 As Nullable(Of Integer)

    Public Property DEVOLUCION As Nullable(Of Integer)

    Public Property TOTAL As Nullable(Of Integer)


End Class
