
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class VR_NotaCompra

    Public Property caanumi As Integer

    Public Property caafdoc As Nullable(Of Date)

    Public Property caaprov As Nullable(Of Integer)

    Public Property cmdesc As String

    Public Property cmrsocial As String

    Public Property cmnit As String

    Public Property cmtelf As String

    Public Property caanfac As String

    Public Property caatven As Nullable(Of Integer)

    Public Property tipocompra As String

    Public Property caafvcred As Nullable(Of Date)

    Public Property caadesc As Nullable(Of Decimal)

    Public Property caatotal As Nullable(Of Decimal)

    Public Property caaemision As Nullable(Of Integer)

    Public Property caafingreso As Nullable(Of Date)

    Public Property cabtc1numi As Nullable(Of Integer)

    Public Property cadesc As String

    Public Property cabcant As Nullable(Of Decimal)

    Public Property cabpcom As Nullable(Of Decimal)

    Public Property cabpcosto As Nullable(Of Decimal)

    Public Property cabsubtot As Nullable(Of Decimal)

    Public Property cabdesc As Nullable(Of Decimal)

    Public Property cabtot As Nullable(Of Decimal)

    Public Property fcarsocial As String

    Public Property fcanfac As Nullable(Of Long)

    Public Property fcaautoriz As Nullable(Of Long)

    Public Property fcaccont As String

    Public Property plazo As Nullable(Of Integer)


End Class
