
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class VR_ProductosMesas

    Public Property canumi As Integer

    Public Property cadesc As String

    Public Property vend1 As Nullable(Of Decimal)

    Public Property totvend1 As Nullable(Of Decimal)

    Public Property vend2 As Nullable(Of Decimal)

    Public Property totvend2 As Nullable(Of Decimal)

    Public Property vend3 As Nullable(Of Decimal)

    Public Property totvend3 As Nullable(Of Decimal)

    Public Property vend4 As Nullable(Of Decimal)

    Public Property totvend4 As Nullable(Of Decimal)


End Class
