
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class VR_ResumenNotas

    Public Property odnumi As Integer

    Public Property odnota As Nullable(Of Integer)

    Public Property odfdoc As Nullable(Of Date)

    Public Property contado As Nullable(Of Decimal)

    Public Property credito As Nullable(Of Decimal)

    Public Property equipos As Nullable(Of Double)

    Public Property pagos As Nullable(Of Decimal)

    Public Property total As Nullable(Of Double)


End Class
