
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class VR_stockActual

    Public Property canumi As Integer

    Public Property cacod As String

    Public Property cadesc As String

    Public Property cadesc2 As String

    Public Property caest As Nullable(Of Boolean)

    Public Property iacprod As Nullable(Of Integer)

    Public Property iacant As Nullable(Of Decimal)

    Public Property cenum As Nullable(Of Boolean)

    Public Property cedesc As String


End Class
