
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class VR_StockDisponible

    Public Property canumi As Integer

    Public Property cadesc As String

    Public Property categoria As String

    Public Property stockSinPedido As Decimal

    Public Property StockSoloPedidos As Decimal

    Public Property StockFinal As Nullable(Of Decimal)


End Class
