
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class Vr_VentasVendidas

    Public Property aanumi As Integer

    Public Property aabdes As String

    Public Property ydnumi As Integer

    Public Property yddesc As String

    Public Property CodVenta As Integer

    Public Property cliente As String

    Public Property facturas As String

    Public Property FechaVenta As Nullable(Of Date)

    Public Property total As Nullable(Of Decimal)


End Class
