
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class Vr_VentasVendedor12Meses

    Public Property numiVendedor As Integer

    Public Property vendedor As String

    Public Property enero As Nullable(Of Decimal)

    Public Property febrero As Nullable(Of Decimal)

    Public Property marzo As Nullable(Of Decimal)

    Public Property abril As Nullable(Of Decimal)

    Public Property mayo As Nullable(Of Decimal)

    Public Property junio As Nullable(Of Decimal)

    Public Property julio As Nullable(Of Decimal)

    Public Property agosto As Nullable(Of Decimal)

    Public Property septiembre As Nullable(Of Decimal)

    Public Property octubre As Nullable(Of Decimal)

    Public Property noviembre As Nullable(Of Decimal)

    Public Property diciembre As Nullable(Of Decimal)

    Public Property total As Nullable(Of Decimal)


End Class
