
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class VR_VistaPedido_PrecioCosto

    Public Property oanumi As String

    Public Property oafdoc As Nullable(Of Date)

    Public Property codcliente As Integer

    Public Property cliente As String

    Public Property codRepartidor As Integer

    Public Property repartidor As String

    Public Property precioCosto As Nullable(Of Decimal)

    Public Property precioVenta As Nullable(Of Decimal)

    Public Property Utilidad As Nullable(Of Decimal)


End Class
