
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class ZY0021

    Public Property ycline As Integer

    Public Property ycnumi As Nullable(Of Integer)

    Public Property ycyanumi As Nullable(Of Integer)

    Public Property ycshow As Nullable(Of Boolean)

    Public Property ycadd As Nullable(Of Boolean)

    Public Property ycmod As Nullable(Of Boolean)

    Public Property ycdel As Nullable(Of Boolean)


End Class
