Public Enum ENLibreria
    TIPO_DATO = 1
    ZONA = 2
    PROVINCIA = 3
    CIUDAD = 4
    TIPO_PRODUCTO = 5
    TIPO_CLIENTE = 6
    TIPO_EMPLEADO = 7
    PRECIO = 8
    TIPO_DOC = 9
    MOVIMIENTO = 10
    MODULOS = 11
    MOVIMIENTO_INV = 12
    CONCEPTO_RECLAMO = 13
    TIPO_ACUERDO = 14
    FRECUENCIA = 15
End Enum
