'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Presentacion.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Public ReadOnly Property _DEFAULT1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_DEFAULT1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ACTUALIZAR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ACTUALIZAR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property add21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property addbt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addbt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property addimg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addimg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ADICIONAR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ADICIONAR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property almacen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("almacen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ANTERIOR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ANTERIOR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ASIGNAR_PEDIDOS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ASIGNAR_PEDIDOS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ASIGNAR_PEDIDOS1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ASIGNAR_PEDIDOS1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property atras() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("atras", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property BARRAS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BARRAS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property BONOS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BONOS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property BONOS_DESC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BONOS_DESC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property BT_ABAJO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BT_ABAJO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property BT_ACTUALIZAR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BT_ACTUALIZAR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property BT_ANTERIOR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BT_ANTERIOR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property BT_ARRIBA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BT_ARRIBA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property BT_COMBO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BT_COMBO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property BT_SIGUIENTE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BT_SIGUIENTE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property BT_ZOOM_MAS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BT_ZOOM_MAS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property BT_ZOOM_MENOS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BT_ZOOM_MENOS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property buscar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buscar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property BUSQUEDA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BUSQUEDA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property cancel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cancel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CANCELAR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CANCELAR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CANDADO_ABIERTO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CANDADO_ABIERTO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CANDADO_CERRADO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CANDADO_CERRADO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Cargar_Archivo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cargar_Archivo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property cargar_asistencia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cargar_asistencia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CHECK_ORI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CHECK_ORI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property checked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("checked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property clase_practica() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clase_practica", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property cliente() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cliente", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CLIENTES() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CLIENTES", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property compra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("compra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CONFIRMACION() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CONFIRMACION", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CONFIRMAR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CONFIRMAR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CONTROL_PEDIDOS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CONTROL_PEDIDOS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CONTROL_RECLAMOS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CONTROL_RECLAMOS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CONTROL_RECLAMOS1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CONTROL_RECLAMOS1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property cuestion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cuestion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property DESCARGAR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DESCARGAR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property DESCUENTOS_FIJOS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DESCUENTOS_FIJOS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property dinases() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dinases", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property dinases1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dinases1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property DISPENSADOR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISPENSADOR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property edit21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property EDITAR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EDITAR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property editar1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("editar1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property EDITAR2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EDITAR2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property efectoS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("efectoS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property elim_fila2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("elim_fila2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property eliminar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eliminar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ELIMINAR1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ELIMINAR1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ELIMINAR2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ELIMINAR2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property EMPLEADOS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EMPLEADOS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ENTRADA_SALIDA_ALM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ENTRADA_SALIDA_ALM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property estadistico() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("estadistico", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property EXCEL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EXCEL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property FERIADO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FERIADO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property fondo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fondo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property FONDO_LOGO1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FONDO_LOGO1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property FONDO1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FONDO1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property fondo11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fondo11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property FONDO2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FONDO2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property FONDO3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FONDO3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property fondoInfo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fondoInfo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property fondoInfo2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fondoInfo2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property fondoInfo3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fondoInfo3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property FondoMercado() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FondoMercado", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property fondopanel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fondopanel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property fondopanel1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fondopanel1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property FORMULARIOS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FORMULARIOS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property GEN_PEDIDOS_AUTOMATICAMENTE_ORI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GEN_PEDIDOS_AUTOMATICAMENTE_ORI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property GENERAR_REPORTE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GENERAR_REPORTE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property generarReporte1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("generarReporte1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property generarReporte2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("generarReporte2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property GRABACION_EXITOSA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GRABACION_EXITOSA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property GRABAR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GRABAR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property grafica() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grafica", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property GUARDAR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GUARDAR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Public ReadOnly Property HOMINIS() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("HOMINIS", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Public ReadOnly Property HOMINIS1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("HOMINIS1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property I256x256_image_capture() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("I256x256_image_capture", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property I32x32_printer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("I32x32_printer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property I512x512_image_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("I512x512_image_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property I512x512_image_remove() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("I512x512_image_remove", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property I512x512_image_update() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("I512x512_image_update", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property I512X512_Intercambio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("I512X512_Intercambio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property I64x64_error() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("I64x64_error", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ic_a() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_a", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ic_c() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_c", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ic_f() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_f", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ic_p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ic_r() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_r", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property iconacercar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconacercar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property iconalejar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconalejar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property IconFondo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconFondo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property imageDefault() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageDefault", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property img1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property img2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property img21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property IMPRIMIR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMPRIMIR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property INFORMATION() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("INFORMATION", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property INICIO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("INICIO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property jpg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jpg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property jpg1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jpg1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property KARDEX() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KARDEX", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property LOGO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LOGO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property man() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("man", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property man_18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("man_18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property man_28() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("man_28", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property MANEJO_PEDIDOS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MANEJO_PEDIDOS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property mapa_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapa_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property mapa_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapa_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property mapa_11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapa_11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property mapa_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapa_12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property mapa_13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapa_13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property mapa_14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapa_14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property mapa_15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapa_15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property mapa_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapa_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property mapa_17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapa_17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property mapa_18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapa_18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property mapa_19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapa_19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property mapa_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapa_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property mapa_20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapa_20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property mapa_21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapa_21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property mapa_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapa_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property mapa_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapa_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property mapa_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapa_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property mapa_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapa_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property mapa_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapa_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property mapa_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapa_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property mapa_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapa_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property mapa_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapa_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property mapa_cliente() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapa_cliente", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property MARCARZONA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MARCARZONA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property mark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property markerA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("markerA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property markerA1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("markerA1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property markerAfondo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("markerAfondo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property markerB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("markerB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property markerBfondo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("markerBfondo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property markerIcono() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("markerIcono", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property markerR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("markerR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Mensaje() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mensaje", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property MENU_QUITAR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MENU_QUITAR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property MONITOREO_PEDIDOS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MONITOREO_PEDIDOS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property MOSTRAR_TODOS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MOSTRAR_TODOS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property movimiento() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("movimiento", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property NOTAS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NOTAS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property NUEVO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NUEVO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property NUEVO2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NUEVO2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property OK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property OPCION_CANCEL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OPCION_CANCEL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property OPCION_OK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OPCION_OK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property pantalla() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pantalla", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property pantalla1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pantalla1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PEDI_ENTRAGA_PEDIDOS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PEDI_ENTRAGA_PEDIDOS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PEDI_PEDIDO_PERIODICO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PEDI_PEDIDO_PERIODICO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PEDI_ULTIMOS_PEDIDOS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PEDI_ULTIMOS_PEDIDOS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PEDIDO_FRECUENTE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PEDIDO_FRECUENTE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PEDIDO_FRECUENTE1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PEDIDO_FRECUENTE1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PEDIDOS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PEDIDOS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PERONAL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PERONAL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property place3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("place3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PLANILLA_SUELDOS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PLANILLA_SUELDOS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PLANILLA_TURNOS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PLANILLA_TURNOS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property plus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property precio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("precio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PRECIO_PRODUCTOS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PRECIO_PRODUCTOS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property printee() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("printee", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property producto() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("producto", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PRODUCTOS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PRODUCTOS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property prohibition() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("prohibition", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PROM_CONSUMO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PROM_CONSUMO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property REGISTRO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("REGISTRO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property reload_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reload_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property REPORTE1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("REPORTE1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property REPORTE2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("REPORTE2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property REPORTE3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("REPORTE3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ResumenSueldos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ResumenSueldos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ROLES() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ROLES", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property rotacionproducto() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rotacionproducto", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property rp_estadoCuentas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rp_estadoCuentas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property RRHH_FERIADO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RRHH_FERIADO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property RRHH_VACACIONES() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RRHH_VACACIONES", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property rubbish() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rubbish", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property SALDO_ALMACEN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SALDO_ALMACEN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property SEGROJO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SEGROJO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property SegVerde() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SegVerde", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property SELECCIONAR_TODOS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SELECCIONAR_TODOS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property sheets() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sheets", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property SIGUIENTE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SIGUIENTE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property street_map() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("street_map", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ToastError() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ToastError", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ToastWarning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ToastWarning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TRANSACCIONES() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TRANSACCIONES", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property trash21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("trash21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ttf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ttf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TURNOS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TURNOS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TXT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TXT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ULTIMO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ULTIMO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property UNCHECK_ORI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UNCHECK_ORI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property user() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property USUARIO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("USUARIO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property USUARIO1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("USUARIO1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property usuario2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("usuario2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property vendedor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vendedor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property VENT_COMPARAR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VENT_COMPARAR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property VENT_FIDELIDAD_CLIENTE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VENT_FIDELIDAD_CLIENTE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property VENT_PAGOS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VENT_PAGOS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property VENT_RESUMEN_NOTAS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VENT_RESUMEN_NOTAS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property VENT_SALDO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VENT_SALDO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ventasCostos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ventasCostos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property verRegistros21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("verRegistros21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property WARNING() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WARNING", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property zona() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zona", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ZONAS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ZONAS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ZOOM_MAS_ORI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ZOOM_MAS_ORI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ZOOM_MENOS_ORI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ZOOM_MENOS_ORI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property zoomin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zoomin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property zoomout() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zoomout", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
